using System.Text;
using Builder.Backends;
using Builder.Instantiation;
using Builder.LlvmEmit;
using SyntaxTree;
using TypeModel.Symbols;
using TypeModel.Types;

namespace Builder.TesseraEmit;

/// <summary>
/// Writes the Phase 9 program as one Tessera module: a record per struct record, an external declaration per C
/// routine called, a routine per routine body, and <c>main</c>. It translates and decides nothing about the
/// language: what to emit is the set the demand collector materialized, and every call is already resolved.
/// </summary>
internal sealed class TesseraWriter
{
    private readonly BackendInput _input;

    /// <summary>Tessera names of the routines this module defines, keyed by the routine's mangled symbol.</summary>
    private readonly Dictionary<string, string> _routineNames = new(comparer: StringComparer.Ordinal);

    private readonly HashSet<string> _usedNames = new(comparer: StringComparer.Ordinal);
    private readonly Dictionary<string, string> _recordNames = new(comparer: StringComparer.Ordinal);
    private readonly StringBuilder _records = new();
    private readonly Dictionary<string, string> _externNames = new(comparer: StringComparer.Ordinal);
    private readonly StringBuilder _externs = new();

    public TesseraWriter(BackendInput input)
    {
        _input = input;
    }

    /// <summary>The Tessera names of the routines the module defines.</summary>
    public IReadOnlyCollection<string> DefinedRoutineNames => _routineNames.Values;

    /// <summary>Writes the module.</summary>
    public string Write()
    {
        List<(RoutineInfo Info, Statement Body)> routines = CollectRoutines();
        foreach ((RoutineInfo info, Statement _) in routines)
        {
            _routineNames[key: LlvmEmitter.MangleRoutineName(routine: info)] =
                UniqueName(wanted: Sanitize(text: LlvmEmitter.MangleRoutineName(routine: info)));
        }

        var definitions = new StringBuilder();
        foreach ((RoutineInfo info, Statement body) in routines)
        {
            definitions.Append(value: new TesseraRoutineWriter(module: this, routine: info, body: body).Write());
            definitions.Append(value: '\n');
        }

        string main = WriteMain(routines: routines);

        var module = new StringBuilder();
        module.Append(value: "// Generated by the RazorForge builder's Tessera backend.\n\n");
        module.Append(value: _records);
        module.Append(value: _externs);
        module.Append(value: definitions);
        module.Append(value: main);
        return module.ToString();
    }

    // ── What to emit ──────────────────────────────────────────────────────────

    /// <summary>
    /// The routine bodies to define: the user programs' routines, then every body the demand collector
    /// materialized (reached standard library routines, monomorphized and synthesized bodies). Mirrors the LLVM
    /// emitter's set, including its bookkeeping skips (templates, an empty synthesized sentinel, a duplicate).
    /// </summary>
    private List<(RoutineInfo, Statement)> CollectRoutines()
    {
        var result = new List<(RoutineInfo, Statement)>();
        var seen = new HashSet<string>(comparer: StringComparer.Ordinal);

        void Add(RoutineInfo info, Statement? body)
        {
            if (body is null || !seen.Add(item: LlvmEmitter.MangleRoutineName(routine: info)))
            {
                return;
            }

            result.Add(item: (info, body));
        }

        foreach ((Program program, string _, string _) in _input.UserPrograms)
        {
            foreach (RoutineDeclaration routine in program.Declarations.OfType<RoutineDeclaration>())
            {
                if (routine.ResolvedInfo is { } info && !IsSkippedUserRoutine(info: info))
                {
                    Add(info: info, body: BodyOf(routine: routine, info: info));
                }
            }
        }

        foreach ((string _, MonomorphizedBody body) in _input.InstantiatedGenericBodies ??
                                                       new Dictionary<string, MonomorphizedBody>())
        {
            if (body.Info.OwnerType is { IsGenericDefinition: true } ||
                body.Info.OwnerType?.TypeArguments?.Any(predicate: a => a is BuildtimeConstGenericTypeSymbol) ==
                true ||
                body.IsSynthesized && body.Ast.Body is BlockStatement { Statements.Count: 0 })
            {
                continue;
            }

            Add(info: body.Info, body: body.IsSynthesized
                ? body.Ast.Body
                : BodyOf(routine: body.Ast, info: body.Info));
        }

        return result;
    }

    /// <summary>A user routine with no body of its own to emit: a template, a foreign declaration, or one the
    /// demand collector did not reach.</summary>
    private bool IsSkippedUserRoutine(RoutineInfo info)
    {
        if (info.IsGenericDefinition || info.OwnerType is GenericParameterTypeSymbol or ProtocolTypeSymbol ||
            info.CallingConvention != null)
        {
            return true;
        }

        IReadOnlyCollection<string>? live = _input.LiveRoutineKeys;
        return live is { Count: > 0 } && !live.Contains(value: info.RegistryKey) && !info.IsLambda;
    }

    /// <summary>A declaration's body, or the body the builder wrote for a declaration without one.</summary>
    private Statement? BodyOf(RoutineDeclaration routine, RoutineInfo info)
    {
        bool isStub = routine.Body is null or BlockStatement { Statements.Count: 0 };
        return isStub && _input.SynthesizedBodies?.TryGetValue(key: info.RegistryKey, value: out Statement? stub) ==
               true
            ? stub
            : routine.Body;
    }

    // ── Names ─────────────────────────────────────────────────────────────────

    /// <summary>The Tessera routine a call to <paramref name="routine"/> goes to: its definition in this module,
    /// or for a C routine, its external declaration.</summary>
    public string RoutineName(RoutineInfo routine)
    {
        if (routine.CallingConvention == "C")
        {
            return ExternName(routine: routine);
        }

        string symbol = LlvmEmitter.MangleRoutineName(routine: routine);
        return _routineNames.TryGetValue(key: symbol, value: out string? name)
            ? name
            : throw new NotSupportedException(
                message: $"The Tessera backend found a call to {symbol}, which has no body in this build.");
    }

    private string ExternName(RoutineInfo routine)
    {
        string symbol = routine.LinkSymbol ?? routine.Name;
        if (_externNames.TryGetValue(key: symbol, value: out string? name))
        {
            return name;
        }

        name = UniqueName(wanted: "c_" + Sanitize(text: symbol));
        _externNames[key: symbol] = name;
        string parameters = string.Join(separator: ", ",
            values: routine.Parameters.Select(selector: p => $"%{p.Name}: {TypeText(type: p.Type)}"));
        _externs.Append(value: $"#[external(\"c\"), symbol(\"{symbol}\")]\n" +
                               $"routine {name}({parameters}) -> {TypeText(type: routine.ReturnType)}\n\n");
        return name;
    }

    private string UniqueName(string wanted)
    {
        string name = wanted;
        for (int i = 2; !_usedNames.Add(item: name); i++)
        {
            name = $"{wanted}_{i}";
        }

        return name;
    }

    /// <summary>A Tessera identifier for a builder name: letters and digits kept, every other run of
    /// characters one underscore, the routine attribute prefix (<c>[member] </c>) dropped.</summary>
    private static string Sanitize(string text)
    {
        text = text.Trim(trimChar: '"');
        string body = text.StartsWith(value: '[') && text.IndexOf(value: "] ", comparisonType: StringComparison.Ordinal)
            is var close and > 0
            ? text[(close + 2)..]
            : text;
        var sb = new StringBuilder(capacity: body.Length);
        foreach (char c in body)
        {
            if (char.IsAsciiLetterOrDigit(c: c))
            {
                sb.Append(value: c);
            }
            else if (sb.Length > 0 && sb[^1] != '_')
            {
                sb.Append(value: '_');
            }
        }

        string name = sb.ToString()
                        .TrimEnd(trimChar: '_');
        return name.Length == 0 || char.IsAsciiDigit(c: name[0])
            ? "rf_" + name
            : name;
    }

    // ── Types ─────────────────────────────────────────────────────────────────

    /// <summary>The Tessera spelling of a builder type.</summary>
    public string TypeText(TypeSymbol? type)
    {
        switch (type)
        {
            case null:
                return "Void";
            case RecordTypeSymbol { BackendType: "void" }:
                return "Void";
            case VariantTypeSymbol variant:
                throw new NotSupportedException(
                    message: $"The Tessera backend does not translate variant types yet ({variant.FullName}).");
            case TupleTypeSymbol { ElementTypes.Count: >= 2 and <= 4 } tuple:
                return $"({string.Join(separator: ", ", values: tuple.ElementTypes.Select(selector: TypeText))})";
            case RecordTypeSymbol { BackendType: { } backend } record:
                return PrimitiveTypeText(record: record, backend: backend);
            case RecordTypeSymbol { IsGenericDefinition: false } record:
                return RecordName(record: record);
            default:
                throw new NotSupportedException(
                    message: $"The Tessera backend does not translate {type.GetType().Name} '{type.FullName}' yet.");
        }
    }

    /// <summary>True for the unit type <c>None</c>, which has no value.</summary>
    public static bool IsVoid(TypeSymbol? type)
    {
        return type is null or RecordTypeSymbol { BackendType: "void" };
    }

    private static string PrimitiveTypeText(RecordTypeSymbol record, string backend)
    {
        string? byName = record.BareName switch
        {
            "S8" or "S16" or "S32" or "S64" or "S128" or "U8" or "U16" or "U32" or "U64" or "U128" => record.BareName,
            "Bool" => "Bool",
            "Byte" => "U8",
            "B16" => "F16",
            "B32" => "F32",
            "B64" => "F64",
            "BF16" => "BF16",
            _ => null
        };
        if (byName != null)
        {
            return byName;
        }

        // A choice is its signed underlying integer and a flags set its unsigned one, as in the LLVM emitter.
        if (backend.Length > 1 && backend[0] == 'i' && int.TryParse(s: backend[1..], result: out int bits))
        {
            switch (record)
            {
                case ChoiceTypeSymbol:
                    return $"S{bits}";
                case FlagsTypeSymbol:
                    return $"U{bits}";
            }
        }

        throw new NotSupportedException(
            message: $"The Tessera backend has no translation for the primitive type {record.FullName} ({backend}).");
    }

    /// <summary>The Tessera record for a struct record, declared on first use with its fields in order.</summary>
    private string RecordName(RecordTypeSymbol record)
    {
        if (_recordNames.TryGetValue(key: record.FullName, value: out string? name))
        {
            return name;
        }

        name = UniqueName(wanted: Sanitize(text: record.FullName));
        _recordNames[key: record.FullName] = name;
        var text = new StringBuilder();
        text.Append(value: $"record {name}\n");
        if (record.MemberVariables.Count < 2)
        {
            // Tessera gives a one-field record the field's own representation unless it is #aggregate. The
            // builder lays every struct record out as a struct, so keep that.
            text.Insert(index: 0, value: "#aggregate\n");
        }

        foreach (MemberVariableInfo field in record.MemberVariables)
        {
            text.Append(value: $"    {field.Name} : {TypeText(type: field.Type)}\n");
        }

        _records.Append(value: text)
                .Append(value: '\n');
        return name;
    }

    // ── Entry ─────────────────────────────────────────────────────────────────

    /// <summary><c>main</c>: initializes the runtime, then runs the entry module's <c>start</c>.</summary>
    private string WriteMain(List<(RoutineInfo Info, Statement Body)> routines)
    {
        string? entry = _input.EntryModule;
        RoutineInfo start = routines.Select(selector: r => r.Info)
                                    .FirstOrDefault(predicate: r =>
                                         r.OwnerType == null &&
                                         LlvmEmitter.MangleRoutineName(routine: r)
                                                    .Trim(trimChar: '"')
                                                    .EndsWith(value: entry is { Length: > 0 }
                                                         ? $"{entry}.start()"
                                                         : ".start()",
                                                     comparisonType: StringComparison.Ordinal)) ??
                            throw new NotSupportedException(
                                message: $"The Tessera backend found no start() routine in the entry module '{entry}' " +
                                         "among: " + string.Join(separator: ", ",
                                             values: routines.Where(predicate: r => r.Info.OwnerType == null)
                                                             .Select(selector: r =>
                                                                  LlvmEmitter.MangleRoutineName(routine: r.Info))));

        return "#[external(\"c\"), symbol(\"rf_runtime_init\")]\n" +
               "routine rf_runtime_init() -> Void\n\n" +
               "routine main() -> S32\n" +
               "    block entry():\n" +
               "        rf_runtime_init()\n" +
               $"        {RoutineName(routine: start)}()\n" +
               "        return(0)\n";
    }
}
